### Import Libraries

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
A = np.array([[1, 2], [3, 4]])
B = A.reshape(1, -1)
print(B)

[[1 2 3 4]]


### Let's generate some Random Data

In [5]:
input_feature_x = np.array([4, 12, 16, 20, 24, 36, 40]).reshape((-1, 1))
output_y = np.array([4, 17, 10, 18, 22, 38, 33])

### Create the linear regression model and fit on data

In [6]:
my_first_linear_model = LinearRegression()
my_first_linear_model.fit(input_feature_x, output_y)

LinearRegression()

### Find the slope and intercept

In [7]:
my_first_linear_model.coef_

array([0.88368056])

In [8]:
my_first_linear_model.intercept_

1.097222222222225

y = mx + c


y = 0.883*x+1.097

### Get Predictions

In [10]:
prediction_array = np.array([13,16]).reshape(-1,1)
my_first_linear_model.predict(prediction_array)

array([12.58506944, 15.23611111])